### ISSUE TITLE
Barcode Scanner not working - Samsung Tab 4 (Lollipop)

### ISSUE THREAD

**Issue by arkye** [reckpack/Mercado#15]
Works fine:
1. Moto X (1st Gen);
2. Samsung S4
3. Asus ZenFone 6

Working bad:
1. Samsung Tab 4

**Comment by bluew0lv** [comment]
The Samsung Tab 4 is missing autofocus in their camera, ZXING library uses the autofocus to get the barcode.

We cannot use anything that does not have autofocus

"For some, it was an issue with the camera driver.  For others, it is the lack of autofocus with the camera."
